mode: learning
#media_root: /media
#media_url: /media
#base_url: /
media_root: /david/media
media_url: /david/media
base_url: /david
template: hyde.ext.templates.jinja.Jinja2Template
plugins:
    - hyde.ext.plugins.meta.MetaPlugin
    - hyde.ext.plugins.auto_extend.AutoExtendPlugin
    - hyde.ext.plugins.sorter.SorterPlugin
    - hyde.ext.plugins.tagger.TaggerPlugin
    - hyde.ext.plugins.syntext.SyntextPlugin
    - hyde.ext.plugins.textlinks.TextlinksPlugin
context:
    data:
        rss: blog/atom.xml
        author:
            name: David Sánchez Crespillo
            url: "http://sanchezcrespillo.net/david"
        project:
            name: Hyde
            url: "http://hyde.github.com"
            install: "http://hyde.github.com/install.html"
        kd2x3:
          - title: 01. Makumba
            url: mp3_KD2X3_-_Ben_entonats_-_01_-_Makumba
            description: Popular brasilera - Heitor Villalobos.  
          - title: 02. Without You
            url: mp3_KD2X3_-_Ben_entonats_-_02_-_Without_you
            description: Nilsson - Arr. Toni Salvà Andreu.
          - title: 03. Sin ti
            url: mp3_KD2X3_-_Ben_entonats_-_03_-_Sin_ti
            description: P. Guizar - Arr. Pep Alarcón Pinya.
          - title: 04. Come Together
            url: mp3_KD2X3_-_Ben_entonats_-_04_-_Come_together
            description: J. Lennon and P. McCartney. Arr. David Sánchez Crespillo
        cancionesdecampamento2007:
          - title: 01. Buenos días
            url: canciones_de_campamento/01_buenos_dias
            lyrics: canciones_de_campamento/letras/01.buenos_dias.pdf
            score: canciones_de_campamento/partituras/partitura_buenos_dias.pdf
          - title: 02. Canto de reunión
            url: canciones_de_campamento/02_canto_de_reunion_electrico
            lyrics: canciones_de_campamento/letras/02.canto_de_reunion.pdf
            score: canciones_de_campamento/partituras/partitura_canto_de_reunion.pdf
          - title: 03. Qué bonito es pasear
            url: canciones_de_campamento/03_que_bonito_es_pasear
            lyrics: canciones_de_campamento/letras/03.que_bonito_es_pasear.pdf
            score: canciones_de_campamento/partituras/partitura_que_bonito_es_pasear.pdf
          - title: 04. Llamada al Himno del Fuego
            url: canciones_de_campamento/04_llamada_al_himno_del_fuego_electrico
            lyrics: canciones_de_campamento/letras/04.llamada_al_himno_de_fuego.pdf
            score: canciones_de_campamento/partituras/partitura_llamada_al_himno_de_fuego.pdf
          - title: 05. Amigo
            url: canciones_de_campamento/05_amigo
            lyrics: canciones_de_campamento/letras/05.amigo.pdf
          - title: 06. Mirando la tierra desde el cielo
            url: canciones_de_campamento/06_mirando_la_tierra_desde_el_cielo
            lyrics: canciones_de_campamento/letras/06.mirando_la_tierra_desde_el_cielo.pdf
          - title: 07. Despedida del Himno del Fuego
            url: canciones_de_campamento/07_despedida_del_himno_del_fuego
            lyrics: canciones_de_campamento/letras/07.despedida_del_himno_de_fuego.pdf
          - title: 08. Buenos días (acústico)
            url: canciones_de_campamento/08_buenos_dias_acustico
            lyrics: canciones_de_campamento/letras/01.buenos_dias.pdf
            score: canciones_de_campamento/partituras/partitura_buenos_dias.pdf
          - title: 09. Canto de reunión (acústico)
            url: canciones_de_campamento/09_canto_de_reunion_acustico
            lyrics: canciones_de_campamento/letras/02.canto_de_reunion.pdf
            score: canciones_de_campamento/partituras/partitura_canto_de_reunion.pdf
          - title: 10. Qué bonito es pasear (acústico)
            url: canciones_de_campamento/10_que_bonito_es_pasear_acustico
            lyrics: canciones_de_campamento/letras/03.que_bonito_es_pasear.pdf
            score: canciones_de_campamento/partituras/partitura_que_bonito_es_pasear.pdf
          - title: 11. Llamada al Himno del Fuego (acústico)
            url: canciones_de_campamento/11_llamada_al_himno_de_fuego_acustico
            lyrics: canciones_de_campamento/letras/04.llamada_al_himno_de_fuego.pdf
            score: canciones_de_campamento/partituras/partitura_llamada_al_himno_de_fuego.pdf
          - title: 12. Valores únicos (instrumental)
            url: canciones_de_campamento/12_valores_unicos
          - title: 13. Construyendo (instrumental)
            url: canciones_de_campamento/13_construyendo
        menu:
          - title: Home
            url: index.html
          - title: CV
            url: cv.html
          - title: ICT
            url: ict.html
          - title: Music
            url: music.html
          - title: Labas Rytas
            url: /labas_rytas/
          - title: Blog
            type: node
            url: blog/index.html
        social:
          - title: LinkedIn
            url: http://www.linkedin.com/in/davidsanchezcrespillo
            image: img/linkedin.png
          - title: Facebook
            url: http://www.facebook.com/davidsanchezcrespillo
            image: img/facebook.png
          - title: Slideshare
            url: http://www.slideshare.net/dinopmi
            image: img/slideshare.png
          - title: Wikipedia
            url: http://es.wikipedia.org/wiki/Usuario:Dinopmi
            image: img/wikipedia.png
          - title: Hispasonic
            url: http://www.hispasonic.com/dinopmi
            image: img/hispasonicos.png
          - title: Youtube
            url: http://www.youtube.com/dinopmi
            image: img/youtube.png
          - title: Github
            url: https://github.com/davidsanchezcrespillo
            image: img/github.png

meta:
    nodemeta: meta.yaml
    created: !!timestamp 2010-01-01 00:00:00
    author: David Sánchez Crespillo
    charset: UTF-8
sorter:
    time:
        attr:
            - meta.created
        reverse: true
        filters:
            source.kind: html
            meta.listable: true
tagger:
    sorter: time
    archives:
        blog:
            source: blog
            target: tags
            template: tagged_posts.j2
            archive_extension: html

